### ISSUE TITLE
Error in demo with updated Typr.js

### ISSUE THREAD

**Issue by dhowe** [photopea/Typr.js#57]
Running the demo from the cloned repo (after update to support woff and var fonts) gives an error on both woff and non-woff fonts:

<img width="663" alt="image" src="https://github.com/user-attachments/assets/660b9069-5e6a-4aa0-ba15-41946f730f01" />

related: #7, #56

**Comment by photopea** [comment]
Hi, I have updated Typr.U.js, it should work now.

**Comment by dhowe** [comment]
Hi, I'm still seeing an error with woffs in the demo. For example, if I download and drag this font: https://fonts.gstatic.com/s/montserrat/v29/JTUFjIg1_i6t8kCHKm459Wx7xQYXK0vOoz6jq6R8aXw.woff
I get an error about the missing pako lib:

```
Typr.js:77 Uncaught ReferenceError: pako is not defined
    at woffToOtf (Typr.js:77:17)
    at Typr.parse (Typr.js:92:27)
    at fontLoaded (index.html:97:16)
    at r.onload (index.html:89:29)
```

see https://github.com/processing/p5.js/issues/7707

**Comment by photopea** [comment]
you need to include the pako.js library to your project, so that Typr.js can process WOFF files.

**Comment by dhowe** [comment]
Understood. Just to note that it is a bit confusing as the first line of the README says that woff is supported, yet this is only true with an external library (and not in the demo).

Anyhow, would be great to get your thoughts on [this patch](https://github.com/processing/p5.js/pull/7716#event-17214659890)
